version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    image: revso/movies-restful
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: